### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kris-Driv** [BlockHorizons/FactionsPE#1]
- [x] Add __description__ command
- [x] Add __info__ command
- [x] Add __name__ command
- [ ] Add __title__ command
- [x] Add __flag__ command
- [x] Add __version__ command
- [x] Fix PureChat support
- [ ] Use __floats__ instead of __integers__ for power
- [ ] Add 'argument swapping' for commands
- [x] Power shouldn't be reduced when claiming land
- [ ] Correct my lazy implementation of MySQL support.
- [x] Rewrite purge code. It should be configurable but now it disbands all factions with inactivity longer than week
- [ ] Finish __power__ & __claim-all__ command 
- [x] All permissions and flags are saved although all have standard values
- [x] Respawn players in faction home
- [ ] Error CombatEngine line 64
- [ ] Money is not showing up as floats if supported by Economy plugin
- [ ] Add more settings for hud
- [ ] Multi factions (member can have more than one faction)

**Comment by Sandertv** [comment]
Make sure to tell me if I can help with anything.

**Comment by Kris-Driv** [comment]
MySQL support is kinda useless at this point. Kinda same issue when you try to push a commit without fetching repository. No idea how to explain it correctly :smile:

**Comment by Kris-Driv** [comment]
I made MySQL support in lazy style, saving arrays (permissions, members, flags etc.) as json strings instead of new tables. Saying in case you feel like correcting it

**Comment by Thunder33345** [comment]
well you can put it in projects todo a new tab for people who have too many time on hands to fix it

**Comment by Thunder33345** [comment]
it would also be nice to document more things this pugin seems quite big and promising so API docs for other devs to build compatibility will be nice

**Comment by Kris-Driv** [comment]
@Thunder33345 working on commenting stuff and creating API docs along with wiki.

**Comment by Sandertv** [comment]
I'm just gonna go ahead and make a Gitter chat room for the organization. That'll make talking a bit easier.

**Comment by Kris-Driv** [comment]
@Sandertv sure, and add the link with gitter badge to readme.

**Comment by Kris-Driv** [comment]
Plugin will be v1.0.0 when this list is complete.

**Comment by Thunder33345** [comment]
actually doing a pre release would be nice a dev build using poggit would be nice too

>Grab the latest .phar file from release section and insert into your server's plugin folder

but there's no phar or releases!

**Comment by Sandertv** [comment]
@Chris-Prime I'll take a look and see if I can improve the MySQL implementation.

**Comment by Sandertv** [comment]
Added info command to the TODO list..

**Comment by asyncthreading** [comment]
@Sandertv @Chris-Prime Maybe add DTR?

**Comment by Kris-Driv** [comment]
What's that? @akaSnapy 

Oh, if you're speaking about relationships then it's already implemented. ``/f relation``

**Comment by asyncthreading** [comment]
DTR=Deaths To Raidable.
1member means x/1 DTR
2 members = x/2 DTR etc..
If you're on 1 DTR and you/other member die this means you went "Raidable" so everyone can bypass your claim until the dtr regens back.

**Comment by asyncthreading** [comment]
Or each value from 0.01-1DTR

**Comment by Kris-Driv** [comment]
Sounds good, but I don't think I will be implementing this into core. I could make it into separate plugin. But I still don't get the mechanics could you elaborate more by creating new issue?

**Comment by asyncthreading** [comment]
Here's how it would work. You would calculate how much DTR a faction gets by dividing its players by 2, for example, a 15 man faction would get a maximum of 7.5 DTR. That means when 8 people die, the faction goes raidable.

When a faction is raidable, enemy factions can edit terrain, open chests, kill mobs, etc on there claimed land.

DTR regenerates slowly, so if a faction got to 1 DTR, they could safely wait it out and they would get back up to their max DTR. A faction that goes raidable could do this too, but when they go raidable, there is a "DTR Freeze" where they stop regenerating, this should last about 2.5 hours.

**Comment by asyncthreading** [comment]
@Chris-Prime

**Comment by asyncthreading** [comment]
The DTR freezing can be configurated also

**Comment by Sandertv** [comment]
That's quite an interesting concept.

**Comment by asyncthreading** [comment]
If your faction's DTR goes below 0, you are raidable.
The DTR freeze is the time after a death until you will be able to regenerate DTR.
If you are raidable, your DTR will still regenerate after the DTR freeze time (configurable) and once it goes above 0, you will no longer be raidable.

**Comment by asyncthreading** [comment]
this can be also selected if its on or no.
factions-dtr=false/true
